
const DEFAULT_MESSAGES_CACHE = 100;
const DEFAULT_RECV_MESSAGES_CACHE = 50;
const MAXIMUM_GET_LATEST_MESSAGE_LENGTH = 50;

export {
    DEFAULT_MESSAGES_CACHE,
    DEFAULT_RECV_MESSAGES_CACHE,
    MAXIMUM_GET_LATEST_MESSAGE_LENGTH
}